language: python

cache: pip

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages:
      - libstdc++6
      - libfuzzy-dev

python:
    - "2.7"
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"

install:
    - pip install -U nose
    - pip install coveralls
    - pip install codecov
    - pip install requests-mock pytest
    - pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip
    - pip install git+https://github.com/kbandla/pydeep.git
    - pip install python-magic
    - pip install .
    - pushd tests
    - git clone https://github.com/viper-framework/viper-test-files.git
    - popd

script:
    - nosetests --with-coverage --cover-package=pymisp tests/test_offline.py

after_success:
    - codecov
    - coveralls
