[tool.poetry]
name = "pymisp"
version = "2.4.194"
description = "Python API for MISP."
authors = ["RaphaÃ«l Vinot <raphael.vinot@circl.lu>"]
license = "BSD-2-Clause"
repository = "https://github.com/MISP/PyMISP"
documentation = "https://pymisp.readthedocs.io"

readme = "README.md"

classifiers=[
    'License :: OSI Approved :: BSD License',
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Operating System :: POSIX :: Linux',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Intended Audience :: Information Technology',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Topic :: Security',
    'Topic :: Internet'
]

include = [
    "CHANGELOG.txt",
    "pymisp/data/*.json",
    "pymisp/data/misp-objects/schema_objects.json",
    "pymisp/data/misp-objects/schema_relationships.json",
    "pymisp/data/misp-objects/objects/*/definition.json",
    "pymisp/data/misp-objects/relationships/definition.json",
    "pymisp/tools/pdf_fonts/Noto_TTF/*"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/MISP/PyMISP/issues"
"Source" = "https://github.com/MISP/PyMISP"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.32.3"
python-dateutil = "^2.9.0.post0"
deprecated = "^1.2.14"
extract_msg = {version = "^0.48.5", optional = true}
RTFDE = {version = "^0.1.1", optional = true}
oletools = {version = "^0.60.1", optional = true}
python-magic = {version = "^0.4.27", optional = true}
pydeep2 = {version = "^0.5.1", optional = true}
lief = {version = "^0.14.1", optional = true}
beautifulsoup4 = {version = "^4.12.3", optional = true}
validators = {version = "^0.28.0", optional = true}
sphinx-autodoc-typehints = {version = "^2.2.0", optional = true, python = ">=3.9"}
docutils = {version = "^0.21.1", optional = true, python = ">=3.9"}
recommonmark = {version = "^0.7.1", optional = true, python = ">=3.9"}
reportlab = {version = "^4.2.0", optional = true}
pyfaup = {version = "^1.2", optional = true}
publicsuffixlist = {version = "^1.0.0.20240620", optional = true}
urllib3 = {extras = ["brotli"], version = "*", optional = true}
Sphinx =  {version = "^7.3.7", python = ">=3.9", optional = true}

[tool.poetry.extras]
fileobjects = ['python-magic', 'pydeep2', 'lief']
openioc = ['beautifulsoup4']
virustotal = ['validators']
docs = ['sphinx-autodoc-typehints', 'recommonmark', 'sphinx', 'docutils']
pdfexport = ['reportlab']
url = ['pyfaup']
email = ['extract_msg', "RTFDE", "oletools"]
brotli = ['urllib3']

[tool.poetry.group.dev.dependencies]
requests-mock = "^1.12.1"
mypy = "^1.10.0"
ipython = [
    {version = "<8.13.0", python = "<3.9"},
    {version = "^8.18.0", python = ">=3.9"},
    {version = "^8.19.0", python = ">=3.10"}
]
jupyterlab = "^4.2.2"
types-requests = "^2.32.0.20240602"
types-python-dateutil = "^2.9.0.20240316"
types-redis = "^4.6.0.20240425"
types-Flask = "^1.1.6"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry_core>=1.1", "setuptools"]
build-backend = "poetry.core.masonry.api"
