[tool.poetry]
name = "pymisp"
version = "2.4.155"
description = "Python API for MISP."
authors = ["RaphaÃ«l Vinot <raphael.vinot@circl.lu>"]
license = "BSD-2-Clause"
repository = "https://github.com/MISP/PyMISP"
documentation = "https://pymisp.readthedocs.io"


readme = "README.md"

classifiers=[
    'License :: OSI Approved :: BSD License',
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Operating System :: POSIX :: Linux',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Intended Audience :: Information Technology',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Topic :: Security',
    'Topic :: Internet'
]

include = [
    "CHANGELOG.txt",
    "README.md",
    "pymisp/data/*.json",
    "pymisp/data/misp-objects/schema_objects.json",
    "pymisp/data/misp-objects/schema_relationships.json",
    "pymisp/data/misp-objects/objects/*/definition.json",
    "pymisp/data/misp-objects/relationships/definition.json",
    "pymisp/tools/pdf_fonts/Noto_TTF/*"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/MISP/PyMISP/issues"
"Source" = "https://github.com/MISP/PyMISP"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"
python-dateutil = "^2.8.2"
jsonschema = "^4.0"
deprecated = "^1.2.13"
extract_msg = {version = "^0.30.8", optional = true}
RTFDE = {version = "^0.0.2", optional = true}
oletools = {version = "^0.60", optional = true}
python-magic = {version = "^0.4.24", optional = true}
pydeep2 = {version = "^0.5", optional = true}
lief = {version = "^0.11.5", optional = true}
beautifulsoup4 = {version = "^4.10.0", optional = true}
validators = {version = "^0.18.2", optional = true}
sphinx-autodoc-typehints = {version = "^1.12.0", optional = true}
recommonmark = {version = "^0.7.1", optional = true}
reportlab = {version = "^3.6.3", optional = true}
pyfaup = {version = "^1.2", optional = true}
chardet = {version = "^4.0", optional = true}
urllib3 = {extras = ["brotli"], version = "^1.26.7", optional = true}

[tool.poetry.extras]
fileobjects = ['python-magic', 'pydeep2', 'lief']
openioc = ['beautifulsoup4']
virustotal = ['validators']
docs = ['sphinx-autodoc-typehints', 'recommonmark']
pdfexport = ['reportlab']
url = ['pyfaup', 'chardet']
email = ['extract_msg', "RTFDE", "oletools"]
brotli = ['urllib3']

[tool.poetry.dev-dependencies]
requests-mock = "^1.9.3"
mypy = "^0.931"
flake8 = "^4.0.1"
ipython = "^7.32"
jupyterlab = "^3.2.8"
types-requests = "^2.27.7"
types-python-dateutil = "^2.8.8"
types-redis = "^4.1.10"
types-Flask = "^1.1.6"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry_core>=1.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
